### PR TITLE
Fixes #99 Lost frame on req/rep.

### LINKED ISSUE #99: The frame is lost in request response
not sure if this is an issue or correct zmq semantics. In request response socket communication if the message is multiframe on  sending side the first frame is lost on receiving side. To reproduce the issue just change the rrclient.go in example to send request like that:-

err := req.Send(zmq4.NewMsgFromString([]string {"Hello?","Hello!"}))

The result on receiving side will be 
rrworker: 2020/11/02 08:02:42 received request: [Hello!]

The "Hello?" part of the message is lost 

I have read that each request in zmq is prepended with the delimiter frame, may be that what confuses me, because I still expect the number of frames on sending  side be equal to the number of frames receiving  on side.

### PR DESCRIPTION
**Pull request by guidog**
Fixes #99 
Added test for issue #99.
Fixed rep.go.

### CODE REVIEW

File: issue99_test.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
+package zmq4
```
Comment (sbinet) [inline issue99_test.go:1]: please add the needed License blurb (with 2020)

also, I'd rename the file as `rep_test.go`.
or I'd add that test inside `zmq4_reqrep_test.go`

File: issue99_test.go [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+	"time"
+)
+
+var (
+	wg     sync.WaitGroup
+	outMsg Msg
+	inMsg  Msg
+)
+
+func requester(t *testing.T) {
```
Comment (sbinet) [inline issue99_test.go:16]: instead of defining the globals above and these `requester`/`responder` functions, I'd define `func` literals directly inside the `TestIssue99` function.

File: issue99_test.go [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+
+	req := NewReq(context.Background())
+	defer req.Close()
+
+	err := req.Dial("tcp://localhost:5559")
```
Comment (sbinet) [inline issue99_test.go:21]: instead of hardcoding `5559` as a port, please use the `EndPoint` function from https://github.com/go-zeromq/zmq4/blob/master/zmq4_test.go#L29.

the port would be fetched inside `TestIssue99` and closed around inside the two closures for `requester` and `responder`.

File: issue99_test.go [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+	wg.Done()
+	if err != nil {
+		t.Fatalf("could not send reply: %v", err)
+	}
+	time.Sleep(2 * time.Millisecond)
+}
+
+func TestIssue99(t *testing.T) {
+	wg.Add(2)
+	go requester(t)
```
Comment (sbinet) [inline issue99_test.go:72]: as the `golint` tool says, all the `t.Fatalf` calls in `requester` and in `responder` need to be replaced by:
```go
t.Errorf(...)
return
```

File: rep.go [hunk 5]
```diff
@@ -55,9 +55,9 @@ func (rep *repSocket) Recv() (Msg, error) {
 	defer cancel()
 	var msg Msg
 	err := rep.sck.r.read(ctx, &msg)
-	if err == nil && len(msg.Frames) > 1 {
```
Comment (sbinet) [inline rep.go:58]: I must admit I don't remember why I wrote this...

File: rep.go [hunk 6]
```diff
@@ -55,9 +55,9 @@ func (rep *repSocket) Recv() (Msg, error) {
...
-		msg.Frames = msg.Frames[1:]
-	}
+	// if err == nil && len(msg.Frames) > 1 {
```
Comment (sbinet) [inline rep.go:58]: just remove it instead of commenting it out.

File: issue99_test.go [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+)
+
+func requester(t *testing.T) {
+
+	req := NewReq(context.Background())
+	defer req.Close()
+
+	err := req.Dial("tcp://localhost:5559")
+	if err != nil {
+		wg.Done()
```
Comment (sbinet) [inline issue99_test.go:23]: please remove this, and all other occurrences.
and add a single `defer wg.Done()` at the top of the function.

File: issue99_test.go [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+
+func responder(t *testing.T) {
+
+	//  Socket to talk to clients
+	rep := NewRep(context.Background())
+	defer rep.Close()
+
+	err := rep.Listen("tcp://*:5559")
+	if err != nil {
+		wg.Done()
```
Comment (sbinet) [inline issue99_test.go:50]: ditto.

please add a single `defer wg.Done()` at the top of that function, and remove all other occurrences of `wg.Done()` below.

**Review by sbinet — COMMENTED** [review]
thanks for the PR and apologies for the belated answer.

I do have a couple of nitpicks.
see below.

thanks again.

File: issue99_test.go (hunk 1 above)
Comment (guidog) [reply issue99_test.go:1]: Hi!
Will move the test into zmq4_reqrep_test.go (TestIssue99).

File: issue99_test.go (hunk 3 above)
Comment (guidog) [reply issue99_test.go:21]: Oh nice, will change that.

File: issue99_test.go (hunk 2 above)
Comment (guidog) [reply issue99_test.go:16]: Why?

File: issue99_test.go (hunk 4 above)
Comment (guidog) [reply issue99_test.go:72]: It doesn't make sense to continue the tests when one of these checks fail, that is the reason why I've chosen .Fatalf.
golint needs to learn a lot it seems.

File: rep.go (hunk 6 above)
Comment (guidog) [reply rep.go:58]: I left it in for easy verification of the fix. Will remove it in the final PR.

**Comment by guidog** [comment]
Should be okay now.

File: rep_test.go [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+func TestIssue99(t *testing.T) {
+	var (
+		wg     sync.WaitGroup
+		outMsg zmq4.Msg
+		inMsg  zmq4.Msg
+	)
+
+	ep, err := EndPoint("tcp")
+	if err != nil {
+		t.Errorf("could not find endpoint: %v", err)
```
Comment (sbinet) [inline rep_test.go:25]:
```suggestion
		t.Fatalf("could not find endpoint: %+v", err)
```

File: rep_test.go [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+
+	requester := func() {
+
+		req := zmq4.NewReq(context.Background())
+		defer req.Close()
+		defer wg.Done()
+
+		err := req.Dial(ep)
+		if err != nil {
+			t.Errorf("could not dial: %v", err)
```
Comment (sbinet) [inline rep_test.go:36]:
```suggestion
			t.Errorf("could not dial: %+v", err)
			return
```

File: rep_test.go [hunk 11]
```diff
@@ -0,0 +1,87 @@
...
+		}
+
+		// Test message w/ 3 frames
+		outMsg = zmq4.NewMsgFromString([]string{"ZERO", "Hello!", "World!"})
+		err = req.Send(outMsg)
+		if err != nil {
+			t.Errorf("failed to send: %v", err)
```
Comment (sbinet) [inline rep_test.go:43]:
```suggestion
			t.Errorf("failed to send: %+v", err)
			return
```

File: rep_test.go [hunk 12]
```diff
@@ -0,0 +1,87 @@
...
+		}
+
+		inMsg, err = req.Recv()
+		if err != nil {
+			t.Errorf("failed to recv: %v", err)
```
Comment (sbinet) [inline rep_test.go:48]:
```suggestion
			t.Errorf("failed to recv: %+v", err)
			return
```

File: rep_test.go [hunk 13]
```diff
@@ -0,0 +1,87 @@
...
+
+	responder := func() {
+
+		rep := zmq4.NewRep(context.Background())
+		defer rep.Close()
+		defer wg.Done()
+
+		err := rep.Listen(ep)
+		if err != nil {
+			t.Errorf("could not dial: %v", err)
```
Comment (sbinet) [inline rep_test.go:60]:
```suggestion
			t.Errorf("could not dial: %+v", err)
			return
```

File: rep_test.go [hunk 14]
```diff
@@ -0,0 +1,87 @@
...
+		}
+
+		//  Wait for next request from client
+		msg, err := rep.Recv()
+		if err != nil {
+			t.Errorf("could not recv request: %v", err)
```
Comment (sbinet) [inline rep_test.go:66]:
```suggestion
			t.Errorf("could not recv request: %+v", err)
			return
```

File: rep_test.go [hunk 15]
```diff
@@ -0,0 +1,87 @@
...
+		}
+
+		//  Send reply back to client
+		err = rep.Send(msg)
+		if err != nil {
+			t.Errorf("could not send reply: %v", err)
```
Comment (sbinet) [inline rep_test.go:72]:
```suggestion
			t.Errorf("could not send reply: %+v", err)
			return
```

File: rep_test.go [hunk 16]
```diff
@@ -0,0 +1,87 @@
...
+		if err != nil {
+			t.Errorf("failed to recv: %v", err)
+		}
+	}
+
+	responder := func() {
+
+		rep := zmq4.NewRep(context.Background())
+		defer rep.Close()
+		defer wg.Done()
```
Comment (sbinet) [inline rep_test.go:56]: shouldn't this `defer` be the first (so the last to execute)?

File: rep_test.go [hunk 17]
```diff
@@ -0,0 +1,87 @@
...
+	ep, err := EndPoint("tcp")
+	if err != nil {
+		t.Errorf("could not find endpoint: %v", err)
+	}
+
+	requester := func() {
+
+		req := zmq4.NewReq(context.Background())
+		defer req.Close()
+		defer wg.Done()
```
Comment (sbinet) [inline rep_test.go:32]: shouldn't this `defer` be the first (so the last to execute)?

File: rep_test.go [hunk 18]
```diff
@@ -0,0 +1,87 @@
...
+		if err != nil {
+			t.Errorf("could not recv request: %v", err)
+		}
+
+		//  Send reply back to client
+		err = rep.Send(msg)
+		if err != nil {
+			t.Errorf("could not send reply: %v", err)
+		}
+		time.Sleep(2 * time.Millisecond)
```
Comment (sbinet) [inline rep_test.go:74]: perhaps I'm missing something (wouldn't be the first), but it seems to me this `sleep` isn't necessary, thanks to the `WaitGroup`, is it?

File: rep_test.go [hunk 19]
```diff
@@ -0,0 +1,87 @@
...
+
+	wg.Add(2)
+
+	go requester()
+	go responder()
+
+	wg.Wait()
+
+	if len(outMsg.Frames) != len(inMsg.Frames) {
+		t.Error("message length mismatch")
```
Comment (sbinet) [inline rep_test.go:85]:
```suggestion
	if got, want := len(outMsg.Frames), len(inMsg.Frames); got != want {
		t.Fatalf("message length mismatch: got=%d, want=%d", got, want)
```

**Review by sbinet — COMMENTED** [review]
still a couple of nit-picks.

the `golint` suggestion was actually to replace `t.Fatal` with `t.Error + return` :)
(as it seems you are not supposed to call `t.Fatal` in another goroutine than the `TestXXX` one. it was news to me as well, the first time I saw that `golint` diagnostic).

thanks again.

File: rep_test.go (hunk 16 above)
Comment (guidog) [reply rep_test.go:56]: I don't think does matter in this case -- it's a test.
The sockets Close() will be called which frees the resources.

File: rep_test.go (hunk 18 above)
Comment (guidog) [reply rep_test.go:74]: True.

File: rep_test.go (hunk 12 above)
Comment (guidog) [reply rep_test.go:48]: Come on...

File: rep_test.go (hunk 19 above)
Comment (guidog) [reply rep_test.go]: Done. That's it.

File: rep_test.go (hunk 16 above)
Comment (sbinet) [reply rep_test.go:56]: sure, it's a test, but in my experience, I noticed a lot of code is written by copy-pasting.
in effect, bad code can spread like wild fire "because it was just to show something" or "it was just a test".

I certainly don't claim I am clear of never having cut that corner, but I try not to.
could you please move that `defer` up?
thanks a lot.

File: rep_test.go (hunk 12 above)
Comment (sbinet) [reply rep_test.go:48]: well, the `%+v` can be quite instrumental in giving the whole "stack" of errors (via the `errors.Unwrap` mechanism).
and the `return` is needed to replicate the original `t.Fatal` code flow.

**Comment by sbinet** [comment]
ping?

**Comment by guidog** [comment]
pong!
I think I did what was necessary to fix the bug, that's why I've been so silent.

**Comment by sbinet** [comment]
hum... ok. I won't push this further.
would you be ok if I merge this in with the fixes I've suggested?

if you do, please also send another PR adding yourself to the authors+contributors files against the [go-zeromq/license](https://github.com/go-zeromq/license) repository?

thanks.

**Comment by guidog** [comment]
Sure go ahead and merge it.

Will add myself to the other repo.
Any explanation why that is needed?

**Comment by sbinet** [comment]
needs https://github.com/go-zeromq/license/pull/7

**Comment by sbinet** [comment]
it's mostly cargo-culting, I guess, but that's how all other orgs I am working in/with are operating :)
