### PR TITLE
Fix splitAddr to properly join host and port for ipv6

### LINKED ISSUE #83: Unable to dial ipv6 addresses
The reassembly dial address from string "tcp://[aaa:bbb::ccc]:55555" not working properly and tries to dual  "aaa:bbb::ccc:55555" instead of "[aaa:bbb::ccc]:55555"

### PR DESCRIPTION
**Pull request by egorse**
Fix #83

### CODE REVIEW

File: utils_test.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
+package zmq4
```
Comment (sbinet) [inline utils_test.go:1]: please add the copyright header blurb.

File: utils_test.go [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+			network: "tcp",
+			addr:    "[::1]:7000",
+			err:     nil,
+		},
+	}
+	for _, tC := range testCases {
+		t.Run(tC.desc, func(t *testing.T) {
+			network, addr, err := splitAddr(tC.v)
+			if network != tC.network {
+				t.Fatalf("unexpected network: %v", addr)
```
Comment (sbinet) [inline utils_test.go:39]:
```suggestion
				t.Fatalf("unexpected network: got=%v, want=%v", network, tC.network)
```

File: utils_test.go [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+			}
+			if addr != tC.addr {
+				t.Fatalf("unexpected address: %v", addr)
```
Comment (sbinet) [inline utils_test.go:42]:
```suggestion
				t.Fatalf("unexpected address: got=%q, want=%q", addr, tC.addr)
```

File: utils_test.go [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+			}
+			if err != tC.err {
```
Comment (sbinet) [inline utils_test.go:44]: because of the "new" error handling (and the wrapped errors), it's better to compare for the error strings (`error.Error() string`) than between error values.

File: utils_test.go [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+		},
+		{
+			desc:    "tcp ipv6",
+			v:       "tcp://[::1]:7000",
+			network: "tcp",
+			addr:    "[::1]:7000",
+			err:     nil,
+		},
+	}
+	for _, tC := range testCases {
```
Comment (sbinet) [inline utils_test.go:35]: we prefer to name this just `tc`.

**Comment by egorse** [comment]
PR updated. All addressed comments should be resolved. Made go-zeromq/license#5

**Comment by sbinet** [comment]
thanks & welcome :)
